backend:
  name: 'github'
  branch: 'master'
  repo: 'logotip4ik/blog'

site_url: 'https://blog.bogdankostyuk.xyz'

media_folder: 'public/images'
public_folder: '/images'

collections:
  - label: 'Posts'
    name: 'posts'
    folder: 'posts'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        required: true
      - label: 'Description'
        name: 'description'
        widget: 'string'
        required: true
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        required: true
      - label: 'Featured Image'
        name: 'image'
        widget: 'image'
        required: false
        allow_multiple: false
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        allow_add: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
